# Generated by Django 3.0.3 on 2020-05-21 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gogo', '0002_topic_last'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='topp',
            new_name='top_name',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='last',
        ),
    ]
