# Generated by Django 3.0.3 on 2020-05-21 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('give', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='jacob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='username',
        ),
    ]
